---
- name: MySQL credentials
  template:
    src=my_cnf_client.j2
    dest=/root/.my.cnf
    owner=root group=root mode=0600
  sudo: yes

- name: Create bin directory
  file:
    path=/root/bin
    owner=root group=root mode=755
    state=directory
  sudo: yes

- name: Tables to exclude from backup
  copy:
    src=tables2exclude
    dest=/root/bin/tables2exclude
    owner=root group=root
  sudo: yes

- name: XtraBackup wrapper script
  template:
    src=xtbackup.sh.j2
    dest=/root/bin/xtbackup.sh
    owner=root group=root mode=755
  sudo: yes

- name: Create a cron job
  cron:
    name="backup DB to S3" minute=30 hour=22
    user="root" job="SHELL=/bin/bash AWS_CONFIG_FILE=/root/.aws_config /root/bin/xtbackup.sh"
    cron_file=backupDB2s3
  sudo: yes
